/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import classmodel.Kategori;
import classmodel.Produk;
import DAO.KategoriDAO;
import DAO.ProdukDAO;
import javax.swing.JOptionPane;
import java.util.List;


/**
 *
 * @author Meisya
 */
public class DialogTambahProduk extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogTambahProduk.class.getName());
    
    private ProdukDAO produkDAO;
    private KategoriDAO kategoriDAO;
    private Produk produk;
    private boolean saved = false;
    private javax.swing.JComboBox<Kategori> cbKategori;
    
    /**
     * Creates new form DialogTambahProduk
     */
    public DialogTambahProduk(java.awt.Frame parent, boolean modal) {
        super(parent, true);
        this.produk = produk;
        initComponents();
        initialize();
    }
    
    private void initialize() {
        produkDAO = new ProdukDAO();
        kategoriDAO = new KategoriDAO();
        setLocationRelativeTo(getParent());
        loadKategoriToComboBox();
        
        if (produk != null) {
            setTitle("Update Produk");
            // Set kategori yang sesuai
            for (int i = 0; i < cbKategori.getItemCount(); i++) {
                Kategori k = cbKategori.getItemAt(i);
                if (k.getKode() == produk.getKodeProduk()) {
                    cbKategori.setSelectedIndex(i);
                    break;
                }
            }
            txtnama.setText(produk.getNama());
            txtharga.setText(String.valueOf(produk.getHarga()));
            txtstock.setText(String.valueOf(produk.getStock()));
        } else {
            setTitle("Tambah Produk");
        }
    }
    
    @SuppressWarnings("unchecked")
    private void loadKategoriToComboBox() {
        cbKategori.removeAllItems();
        List<Kategori> listKategori = kategoriDAO.getForComboBox();
        for (Kategori k : listKategori) {
            cbKategori.addItem(k);
        }
    }

    
    public boolean isSaved() {
        return saved;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnama = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Kategori");

        jLabel3.setText("Harga");

        jLabel4.setText("Stock");

        btnsave.setText("Save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama)
                            .addComponent(txtharga)
                            .addComponent(txtstock)
                            .addComponent(jComboBox1, 0, 198, Short.MAX_VALUE)))
                    .addComponent(btnsave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void saveData() {
        Kategori selectedKategori = (Kategori) cbKategori.getSelectedItem();
        String nama = txtnama.getText().trim();
        String hargaStr = txtharga.getText().trim();
        String stockStr = txtstock.getText().trim();
        
        // Validasi input
        if (selectedKategori == null) {
            JOptionPane.showMessageDialog(this,
                "❌ Pilih kategori!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "❌ Nama produk harus diisi!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "❌ Harga harus diisi!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (stockStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "❌ Stock harus diisi!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int harga = Integer.parseInt(hargaStr);
            int stock = Integer.parseInt(stockStr);
            
            boolean success;
            if (produk == null) {
                // Insert
                Produk newProduk = new Produk();
                newProduk.setKodeProduk(selectedKategori.getKode());
                newProduk.setNama(nama);
                newProduk.setHarga(harga);
                newProduk.setStock(stock);
                success = produkDAO.insert(newProduk);
            } else {
                // Update
                produk.setKodeProduk(selectedKategori.getKode());
                produk.setNama(nama);
                produk.setHarga(harga);
                produk.setStock(stock);
                success = produkDAO.update(produk);
            }
            
            if (success) {
                saved = true;
                dispose();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "❌ Harga dan Stock harus berupa angka!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        saveData();
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogTambahProduk dialog = new DialogTambahProduk(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
